### ISSUE TITLE
variable location has never been used. Does not work for any image.

### ISSUE THREAD

**Issue by krishnasinha** [DavidBenko/MHTML-to-HTML-Decoding-in-C-Sharp#3]
The variable (location) has never been used. However, it has got value assigned. What is the purpose of this variable. Also, the parser does not work for image.

**Comment by DavidBenko** [comment]
@krishnasinha 

Below is the use for the content location header. It was not useful to me when I wrote this, so nothing ever happened with it. Feel free to enter a pull request with support for this header. 

What do you mean it doesn't work for images? Can you be more specific? 

> MHTML defines the naming of objects that are normally referred to by URLs and the means of aggregatingresources that go together. Two MIME headers, Content-Location and Content-Base, are defined in order to resolve references to other content stored locally in related body parts. Content-Base gives an absolute URL base, or "starting point",for relative URLs that appear in other MIME headers and in HTML documents that do not contain any BASE HTML elements. Content-Location specifies the URL that corresponds to the content of the body part that contains this header.
- https://msdn.microsoft.com/en-us/library/ms526265(v=exchg.10).aspx

Thanks

**Comment by DavidBenko** [comment]
Never got back to me. Closing.
