### ISSUE TITLE
Converts HTML file to MHTML?

### ISSUE THREAD

**Issue by kiquenet** [DavidBenko/MHTML-to-HTML-Decoding-in-C-Sharp#4]
any suggestions?

**Comment by DavidBenko** [comment]
@kiquenet I would just write a class that does the opposite of what this class does. Take some HTML, base64 encode it, and write the boundaries.

I believe this is the spec to follow: http://www.ietf.org/rfc/rfc2557.txt

See also: http://stackoverflow.com/a/10000001
